[package]
name = "SimpleRSA"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = "0.5.0"  # For RSA encryption/decryption
rand = "0.8"    # For generating random numbers (used in key generation)
base64 = "0.21" # Optional, for encoding the output as base64
