[package]
name = "shamirs_secret"
version = "0.1.0"
edition = "2021"

[dependencies]
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks.git" }
lambdaworks-crypto = { git = "https://github.com/lambdaclass/lambdaworks.git" }
